### ISSUE TITLE
Xcode 11 GM 2: Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by mikebuss** [ActivBody/activ5-ble-ios#1]
When trying to compile this library using Xcode 11 GM 2 we're getting an error:

"Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler"

![Screen Shot 2019-09-20 at 3 09 22 PM](https://user-images.githubusercontent.com/1574304/65352429-a3cb8400-dbb8-11e9-827a-308db1531571.png)

This is making it difficult for us to update our apps for iOS 13. Is there a recommended way of fixing this? Or, is the only option to wait for a version of the library that was compiled for Swift 5.1?

Thank you!

**Comment by martin-key** [comment]
Hello @mikebuss! 
Thanks for the report, we will update the framework. 
May you try a workaround: 
Go to Xcode -> Click on Pods project on the right pane -> Build Settings -> Activ5Device -> Search for swift version and set it to 5.1
Let me know if that works for you.

**Comment by mikebuss** [comment]
That didn't seem to work for us - we're getting the same error as above. Let us know if we're doing something wrong!

We tried cleaning the project and deleting derived data in between attempts as well.

![err](https://user-images.githubusercontent.com/1574304/65353554-70d6bf80-dbbb-11e9-9d95-828f5bc86fc5.png)

![Screen Shot 2019-09-20 at 3 30 42 PM](https://user-images.githubusercontent.com/1574304/65353648-a67ba880-dbbb-11e9-8a7a-2c2a69c664d0.png)

![Screen Shot 2019-09-20 at 3 25 40 PM](https://user-images.githubusercontent.com/1574304/65353586-851abc80-dbbb-11e9-9c7d-5c433a5b53b6.png)

**Comment by martin-key** [comment]
I have reproduced it with the new Xcode. I am working to precompile and release.

**Comment by martin-key** [comment]
Would you please try:
1. Open your workspace 
2. Click on Pods project
3. Expand Pods folder
4. Find Activ5Device and right click `Activ5Device.framework` then `Show in Finder`
5. Replace the file `Activ5Device.framework` with the one attached here. 
[Activ5Device.framework.zip](https://github.com/ActivBody/activ5-ble-ios/files/3639101/Activ5Device.framework.zip)
<img width="448" alt="Screenshot 2019-09-22 at 0 14 26" src="https://user-images.githubusercontent.com/3859373/65379282-7f61cb80-dcce-11e9-8b32-5ad8fcd4a15c.png">

**Comment by mikebuss** [comment]
That worked on our end. Thanks for the help!

**Comment by mikebuss** [comment]
Will this change be in an official CocoaPods version at some point? If not, we'll just have to automate replacing the file every time the Pods directory is wiped on a `pod install`, `pod update`, etc.

**Comment by martin-key** [comment]
Yup, version 1.0.1 has been deployed like 3 hours ago. You may try it and advice if you find any problems. 
We are preparing a major release that will go out maybe in a month.

**Comment by mikebuss** [comment]
The 1.0.1 pod worked as well. Thanks!

**Comment by martin-key** [comment]
It is quite interesting for me what are you working on. If you want we can chat somewhere and also if you need any info or you need any help, let me know.
