### ISSUE TITLE
Could not find module 'Activ5Device' for target 'x86_64-apple-ios-simulator'; found: arm64, arm, armv7

### ISSUE THREAD

**Issue by frankyyzy** [ActivBody/activ5-ble-ios#2]
When I try to build in Xcode, I am getting an error on the line of code "import Activ5Device":

Could not find module 'Activ5Device' for target 'x86_64-apple-ios-simulator'; found: arm64, arm, armv7

I have done some research and this stackoverflow post seems to address the issue but I can not figure out how to fix it:
https://stackoverflow.com/questions/56957632/could-not-find-module-for-target-x86-64-apple-ios-simulator

Any help would be appreciated!

**Comment by brunohenriquesk1** [comment]
Hello, thanks for reporting the issue @frankyyzy, which version of Xcode are you using? is it happening only with simulators or real devices as well?

**Comment by brunohenriquesk1** [comment]
> When I try to build in Xcode, I am getting an error on the line of code "import Activ5Device":
> 
> Could not find module 'Activ5Device' for target 'x86_64-apple-ios-simulator'; found: arm64, arm, armv7
> 
> I have done some research and this stackoverflow post seems to address the issue but I can not figure out how to fix it:
> https://stackoverflow.com/questions/56957632/could-not-find-module-for-target-x86-64-apple-ios-simulator
> 
> Any help would be appreciated!

Hello, thanks for reporting the issue @frankyyzy, which version of Xcode are you using? is it happening only with simulators or real devices as well?

**Comment by frankyyzy** [comment]
Xcode version: 11.1
When you say update pod, do you mean just type pod update in the Example folder?
Also, for building the app in a real device, do i need a specific team account?
As I am getting this error: 

Showing Recent Messages

Build target Activ5-Device_Tests of project Activ5-Device with configuration Debug
error: No account for team "P6Y2W9RQ54". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. (in target 'Activ5-Device_Tests' from project 'Activ5-Device')error: No signing certificate "iOS Development" found: No "iOS Development" signing certificate matching team ID "P6Y2W9RQ54" with a private key was found. (in target 'Activ5-Device_Tests' from project 'Activ5-Device')

**Comment by frankyyzy** [comment]
running pod update works for me. Thank you!

**Comment by frankyyzy** [comment]
![Screen Shot 2019-10-26 at 9 51 32 AM](https://user-images.githubusercontent.com/35711241/67623101-3a9de880-f7d6-11e9-9755-79a84e7a5080.png)

When I am trying to build this on a real device, I get the following error. Can you help?

**Comment by brunohenriquesk1** [comment]
> ![Screen Shot 2019-10-26 at 9 51 32 AM](https://user-images.githubusercontent.com/35711241/67623101-3a9de880-f7d6-11e9-9755-79a84e7a5080.png)
> 
> When I am trying to build this on a real device, I get the following error. Can you help?

Hi, just change the bundle identifier to something unique and select a dev profile. If you dont have a profile please add one under Xcode preferences -> Accounts.

**Comment by frankyyzy** [comment]
Works for me. Thanks!
